
import LoginButton from '@/components/Blocks/Home/LoginButton';
import HomepageLayout from '@/components/Layouts/HomepageLayout'
import HomeNavigation from '@/components/Navigation/HomeNavigation'
import TinyNote from '@/components/Typography/TinyNote';
import Title from '@/components/Typography/Title';
import Button from '@/components/UI/Button';
import { Metadata } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react'


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Index() {
    return (
        <HomepageLayout>
            <Head>
                <title>Gentletask</title>
            </Head>
            <HomeNavigation />
            <div className="p-0 md:p-3 ">
                <div className="md:rounded relative overflow-hidden min-h-64 py-16 md:py-24 w-full justify-center flex">
                    <div className="md:max-w-3xl w-full px-4 relative mt-8 z-10">
                        <div className="max-w-md">
                            <h1 className='font-normal text-4xl md:text-5xl'>Řiďte svůj život chytře.<br /> <span className='text-blue'>Gentletask</span> bude váš chytrý asistent.</h1>
                            <div className="inline-flex flex-col items-start mt-4 gap-2 w-min">
                                <LoginButton />
                                <TinyNote>Po dobu beta verze je celá aplikace k dispozici zdarma. Poté za 199 Kč měsíčně.</TinyNote>
                            </div>
                        </div>
                        <div className="-z-10 absolute right-0 top-0 -bottom-32 md:-top-24 md:-bottom-32 w-full">
                            <Image fill className=' object-right object-contain' src={"/images/plant.png"} alt={'Gentletask plant'} />
                        </div>
                    </div>
                    <div className="absolute top-0 left-0 right-0 bottom-0 bg-brown-background z-0 pointer-events-none"></div>
                </div>
            </div>
        </HomepageLayout>
    )
}
